### ISSUE TITLE
第一个报错 

### ISSUE THREAD

**Issue by cnruhefangyuan** [spiritLHL/Hang-up-items#1]
root@instance-20210526-2312:~# tightvncserver :1
A VNC server is already running as :1
root@instance-20210526-2312:~# export DISPLAY=localhost:1
root@instance-20210526-2312:~# firefox --profile ~/.alexa/alexa --new-tab 'https://www.alexamaster.net/ads/autosurf/1我的用户号码' &
[1] 7732
root@instance-20210526-2312:~# ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default

**Comment by spiritLHL** [comment]
用的国内机子还是国外机子？国内机子的话容易出问题，试试国外机子的命令吧，事先先kill掉原来的VNC进程先吧

**Comment by cnruhefangyuan** [comment]
用的oracle的机器，然后申请的是韩国首尔的地址。选择的是国外那个指令，运行完报错了

**Comment by spiritLHL** [comment]
你替换了自己的链接吗？如果还是不行留个tg给我，私聊吧

**Comment by cnruhefangyuan** [comment]
> 你替换了自己的链接吗？如果还是不行留个tg给我，私聊吧

替换了，tg：  
https://t.me/ivanjocker

**Comment by spiritLHL** [comment]
已解决，相关问题引申的教程已更新到

[这里](https://github.com/spiritLHL/Alexamaster)
