### ISSUE TITLE
之前不知道哪个脚本导致我的github action被封了，有些脚本偷偷更新加入挖矿

### ISSUE THREAD

**Issue by cikichen** [spiritLHL/Hang-up-items#2]
现在用脚本还得仔细分辨有没有投毒

**Comment by spiritLHL** [comment]
> 现在用脚本还得仔细分辨有没有投毒

我现在只用我信得过的几个库，博客里列出来全部的有几个库是名声不好的

**Comment by spiritLHL** [comment]
> 现在用脚本还得仔细分辨有没有投毒

还有不要用actions执行，整签到这种东西GitHub会封的
